language: rust
os:
  - osx 
cache: cargo

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
    - git config --local user.name "deweycw"
    - git config --local user.email "dewey.christian@gmail.com"
    - name="cms-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - cp target/$TARGET/release/cms $name/
    - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    file: cms_test-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      branch: master
      tags: true


jobs: 
  include:
  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: stable
    script: cargo build --release --target $TARGET
    <<: *DEPLOY_TO_GITHUB

  - name: OSX Binary
    env: TARGET=osx
    rust: stable
    script: cargo build --release --target $TARGET
    <<: *DEPLOY_TO_GITHUB
