language: rust
os:
  - osx 
cache: cargo
dist: trusty


jobs: 
include:
- name: Linux Binary
  env: TARGET=x86_64-unknown-linux-musl
  rust: stable
  before_script: rustup target add $TARGET
  script: cargo build --release --target $TARGET --workspace
  deploy: 
    provider: releases
    file: cms_test-$TRAVIS_TAG-$TARGET.tar.gz
    on: 
      tags: true
      branch: release

- name: OSX Binary
  env: TARGET=osx
  rust: stable
  before_script: rustup target add $TARGET
  script: cargo build --release --target $TARGET --workspace
  deploy: 
    provider: releases
    file: cms_test-$TRAVIS_TAG-$TARGET-x86_64.tar.gz
    on: 
      tags: true
      branch: release
